### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [ ]:
import numpy as np
original= np.random.random((3,28,28))
flat= np.reshape(original, (1,3*28*28))
flat1D= flat.flatten()
print("Shape of original: ", original.shape)
print("Shape of flat: ",flat.shape)
print("Shape of flattened 1D array: ", flat1D.shape)

Shape of original:  (3, 28, 28)
Shape of flat:  (1, 2352)
Shape of flattened 1D array:  (2352,)


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [ ]:
#original
print("original")
print("Dimensions: ",original.ndim)
print("Memory Address: ", original.data)
print("Shape: ", original.shape)
print("Type: ", original.dtype)

#flat
print("\nflat")
print("Dimensions: ",flat.ndim)
print("Memory Address: ", flat.data)
print("Shape: ", flat.shape)
print("Type: ", flat.dtype)

#flat1D
print("\nflat1D")
print("Dimensions: ",flat1D.ndim)
print("Memory Address: ", flat1D.data)
print("Shape: ", flat1D.shape)
print("Type: ", flat1D.dtype)

original
Dimensions:  3
Memory Address:  <memory at 0x7fd5ff6ddd50>
Shape:  (3, 28, 28)
Type:  float64

flat
Dimensions:  2
Memory Address:  <memory at 0x7fd5fd857f30>
Shape:  (1, 2352)
Type:  float64

flat1D
Dimensions:  1
Memory Address:  <memory at 0x7fd5fd6feef0>
Shape:  (2352,)
Type:  float64


### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [ ]:
new_array = (-1) * original
new_array

array([[[-0.32728727, -0.38068735, -0.24023001, ..., -0.96941113,
         -0.97625029, -0.72388561],
        [-0.08900981, -0.28934672, -0.96568845, ..., -0.09622835,
         -0.65390863, -0.46461259],
        [-0.66684467, -0.97494239, -0.83315731, ..., -0.29665125,
         -0.52114542, -0.61220197],
        ...,
        [-0.42379513, -0.11607306, -0.63967817, ..., -0.95037278,
         -0.64127711, -0.76570536],
        [-0.3988694 , -0.17859449, -0.40593418, ..., -0.72374993,
         -0.25728892, -0.51208789],
        [-0.32048436, -0.61753927, -0.0536562 , ..., -0.013546  ,
         -0.499746  , -0.63669665]],

       [[-0.77703449, -0.94707264, -0.21649477, ..., -0.24005022,
         -0.9417447 , -0.30016504],
        [-0.83798615, -0.43276893, -0.46677244, ..., -0.87386655,
         -0.04770251, -0.05982422],
        [-0.83102707, -0.18837651, -0.31419375, ..., -0.99314504,
         -0.72973434, -0.50832611],
        ...,
        [-0.09045988, -0.29221639, -0.07264685, ..., -

In [ ]:
original + new_array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [ ]:
original [1][1][:10]

array([0.83798615, 0.43276893, 0.46677244, 0.36406468, 0.37494707,
       0.18162012, 0.30773396, 0.39267   , 0.2677163 , 0.70125636])

### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [ ]:
print("Shape:",original [2].shape)
print(original[2][:3])

Shape: (28, 28)
[[0.91846008 0.08306145 0.36064354 0.53143742 0.86000597 0.78893384
  0.60755826 0.03084151 0.83982144 0.57763987 0.9987726  0.85768059
  0.56379197 0.62174753 0.28493155 0.45844151 0.49759545 0.18390286
  0.89331202 0.45759821 0.37866055 0.09090534 0.46816098 0.20767729
  0.42282832 0.67394672 0.05239482 0.26393806]
 [0.98482311 0.25183751 0.1617344  0.96805637 0.97591872 0.33731365
  0.78402423 0.37488944 0.54113628 0.58338452 0.50098656 0.82405889
  0.8305535  0.23667379 0.56768151 0.5318403  0.22509097 0.8452554
  0.59341015 0.95480704 0.86880989 0.7353013  0.50101069 0.95442582
  0.12221363 0.96016192 0.12705398 0.38005712]
 [0.9894609  0.5376251  0.76388011 0.66064291 0.15132846 0.02108293
  0.85297303 0.02568576 0.59202356 0.87048262 0.24529242 0.8163048
  0.68353361 0.92622821 0.14221264 0.75379552 0.00126666 0.87283734
  0.08186262 0.47837368 0.24486081 0.08269306 0.03878557 0.45004389
  0.37503691 0.61230565 0.13988498 0.39204075]]


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [ ]:
arr = np.arange(0,100, 2)
arr = np.reshape (arr, (10,5))
arr_t= np.transpose(arr)
print("Array\n",arr)
print("Transpose\n",arr_t)

Array
 [[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]
Transpose
 [[ 0 10 20 30 40 50 60 70 80 90]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 8 18 28 38 48 58 68 78 88 98]]


###Task 7 
Consider the 10x5 array created in Task 6. Find the mean each row and column. You may use in built functions or write your own code.

In [ ]:
mean_r= np.mean(arr,1)
print("Mean Row", mean_r)

mean_c = np.mean(arr,0)
print("Mean Column", mean_c)

Mean Row [ 4. 14. 24. 34. 44. 54. 64. 74. 84. 94.]
Mean Column [45. 47. 49. 51. 53.]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

No, as 50 is not divisible by 3 and hence cannot be arranged in 3x3 form.
Other possible values = 1x50 or 50x1; 2x25 or 25x2; 5x10 or 10x5